{% set version = "0.25.0" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/scikit-image/scikit_image-{{ version }}.tar.gz
  sha256: 58d94fea11b6b3306b3770417dc1cbca7fa9bcbd6a13945d7910399c88c2018c

build:
  skip: true  # [py<310]
  number: 1
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - python-build
    - pip
    - cython >=0.29.24,!=0.29.18,!=3.0.3
    - meson-python
    - numpy
    - pythran
    - packaging >=20.0
  run:
    # https://github.com/scikit-image/scikit-image/blob/main/pyproject.toml#L28
    - python
    - scipy >=1.11.2
    - networkx >=3.0
    - pillow >=10.1
    - imageio >=2.33,!=2.35.0
    - tifffile >=2022.8.12
    - pywavelets >=1.1.1
    - packaging >=21
    - lazy_loader >=0.4
  run_constrained:
    # numpy's run_export sets the lower bound to be 1.19
    # https://github.com/conda-forge/numpy-feedstock/issues/324
    # We must set the lower bound in accordance to scikit-image's
    # runtime requirements
    - numpy >=1.24
    # scikit-image optionally depends on dask-array
    # but pypy doesn't support it
    # which requires numpy, dask-core and toolz (cytoolz for speed)
    - dask-core >=2022.11.0,!=2024.8.0        # [python_impl == 'cpython']
    - toolz >=0.10.0              # [python_impl == 'cpython']
    - cytoolz >=0.11.0            # [python_impl == 'cpython']
    # cloudpickle is necessary to provide the 'processes' scheduler for dask
    - cloudpickle >=3.0         # [python_impl == 'cpython']
    - astropy >=6.0
    - matplotlib-base >=3.7
    - pooch >=1.6.0
    - scikit-learn >=1.2
    - pyamg >=5.2
    - pywavelets >=1.6

# Issues reported upstream. Follow
# https://github.com/scikit-image/scikit-image/issues/4768

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-image/scikit-image/issues/4774 - test_end_points fails on ppc64le with python 3.6, 3.7, 3.8 #4774
{% set tests_to_skip = tests_to_skip + " or test_end_points" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4773 - test_RGB fails on ppc64le with python 3.7 #4773
{% set tests_to_skip = tests_to_skip + " or test_RGB" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4772 - test_periodic_reference fails on ppc64le python 3.7 (conda feedstock) #4772
{% set tests_to_skip = tests_to_skip + " or test_periodic_reference" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4775 - test_hdx_rgb_roundtrip fail son osx with python 3.8 #4775
{% set tests_to_skip = tests_to_skip + " or test_hdx_rgb_roundtrip" %}  # [ppc64le or aarch64 or osx]
# https://github.com/scikit-image/scikit-image/issues/4776 test_hed_rgb_roundtrip fails on osx with python3.8 and ppc64le with python 3.6 #4776
{% set tests_to_skip = tests_to_skip + " or test_hed_rgb_roundtrip" %}  # [ppc64le or aarch64 or osx]
# https://github.com/scikit-image/scikit-image/issues/4778 - test_hed_rgb_float_roundtrip fails on ppc64le python 3.8 #4778
{% set tests_to_skip = tests_to_skip + " or test_hed_rgb_float_roundtrip" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4781 - test_ellipse_rotated fails on python3.8 #4781
{% set tests_to_skip = tests_to_skip + " or test_ellipse_rotated" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4785 - test_fixed_reference fails on ppc64le with python 3.7 #4785
{% set tests_to_skip = tests_to_skip + " or test_fixed_reference" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4782 - test_free_reference fails on ppc64le with python 3.6 #4782
{% set tests_to_skip = tests_to_skip + " or test_free_reference" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4777 - test_uint16 fails on win #4777
{% set tests_to_skip = tests_to_skip + " or test_uint16" %}  # [win]
# TODO: Report this upstream
# It seems that the apply_parallel tests can have relatively small errors on windows
{% set tests_to_skip = tests_to_skip + " or test_apply_parallel_rgb" %}  # [win]


# skip known failure on Windows PyPy builds
{% set tests_to_skip = tests_to_skip + " or test_hough_ellipse_zero_angle or test_hough_ellipse_non_zero" %}  # [win and (python_impl == 'pypy')]
# This used to be a known failure in Python 3.4 that resurfaced in PyPy3.7
# https://github.com/conda-forge/scikit-image-feedstock/pull/91#issuecomment-1153888057
{% set tests_to_skip = tests_to_skip + " or test_wrap_around" %}  # [python_impl == 'pypy']
# uses get_sizeof which returns an error on pypy
{% set tests_to_skip = tests_to_skip + " or test_dask_histogram" %}  # [python_impl == 'pypy']
{% set tests_to_skip = tests_to_skip + " or test_apply_parallel_rgb_channel_axis" %}  # [python_impl == 'pypy']


# These seem to fail on pypy + linux_64
{% set tests_to_skip = tests_to_skip + " or test_clear_border_non_binary_out" %}     # [python_impl == 'pypy']
{% set tests_to_skip = tests_to_skip + " or test_clear_border_non_binary_out_3d" %}  # [python_impl == 'pypy']

# These seem to fail on cpython + linux_64 and seem generally flaky
{% set tests_to_skip = tests_to_skip + " or test_subpix_border" %}
{% set tests_to_skip = tests_to_skip + " or test_max_tree" %}
{% set tests_to_skip = tests_to_skip + " or test_offsets_to_raveled_neighbors_explicit_0" %}   # [python_impl in ('cpython', 'pypy')]
{% set tests_to_skip = tests_to_skip + " or test_offsets_to_raveled_neighbors_explicit_1" %}   # [python_impl in ('cpython', 'pypy')]

# Performance based test, best left for upstream and not conda-forge packaging
{% set tests_to_skip = tests_to_skip + " or test_max_batch_size" %}

# Seems flaky but only on windows- hmaarrfk 2024/06
{% set tests_to_skip = tests_to_skip + " or test_polynomial_weighted_estimation" %}  # [win]

# Downloading all from github just gets us banned.
{% set tests_to_skip = tests_to_skip + " or test_download_all_with_pooch" %}
test:
  requires:
    - pytest
    - pytest-localserver
    # Include pooch to ensure full test coverage
    - pooch  # [not (ppc64le or aarch64)]
    - pip
    - numpydoc
  imports:
    - skimage
  commands:
    # 2023/06/28 -- Seems like pypy + scipy's pip check is broken
    - pip check              # [python_impl == 'cpython']
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    # A warning in numpy that makes tests fail has been fixed in 0.18
    # Remove this then.
    # tests run slowly on ci servers, so we skip them
    - SKIMAGE_TEST_STRICT_WARNINGS=0 pytest --pyargs skimage -k "not ({{ tests_to_skip }})"  # [unix]
    - set "SKIMAGE_TEST_STRICT_WARNINGS=0" & pytest --pyargs skimage -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: http://scikit-image.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Image processing in Python.
  description: |
    scikit-image is a collection of algorithms for image processing.
    It is available free of charge and free of restriction.
    We pride ourselves on high-quality, peer-reviewed code,
    written by an active community of volunteers.
  doc_url: https://scikit-image.org/docs/stable/
  dev_url: https://github.com/scikit-image/scikit-image

extra:
  recipe-maintainers:
    - stefanv
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
    - emmanuelle
    - grlee77
