{% set version = "0.15.dev0.nightly" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  git_url: https://github.com/scikit-image/scikit-image
  patches:
    - pr_3147_simplify_build_process.diff
    - pr_3146_bugfix_seperate_stains_log10.diff
    - pr_3143_supress_warnings_for_flatten_during_testing.diff
    - pr_3126_imageio_preferred_over_PIL.diff
    - pr_3103_bugfix_ellipsis_fitting_32bit.diff
    - pr_3077_feature_transform_geometry.diff
    - pr_3069_feature_rectangle_perimeter.diff
    - pr_3057_feature_bayer2rgb.diff

build:
  number: 1
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - ccache
    - pip
    - cython >=0.23
    - numpy 1.11.3
    - scipy >=0.17
    - numpydoc >=0.6
    - msinttypes  # [win and py<35]
  run:
    - python
    - six >=1.7.3
    - {{ pin_compatible('numpy') }}
    - scipy >=0.17
    - networkx >=1.8
    - pillow >=4.3.0
    - dask-core >=0.15
    - toolz >=0.7.4
    - pywavelets >=0.4.0
    - dask-core >=0.9.0
    - cloudpickle >=0.2.1
    - imageio >=2.1.0
    - matplotlib >=2.0.0

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - skimage
  commands:
    - MPLBACKEND=Agg pytest --pyargs skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
    - ocefpaf
    - soupault
