{% set version = "0.14.1" %} 

package:
  name: scikit-image
  version: {{ version }}

source:
  # pypi sources include the cythonized files.
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  sha256: 86a9b3b4f74f231e0a6bcfd3235dcf3f0118df25dac21201da5e064d681e2c50
  # Github sources don't include the cythonized files
  # url: https://github.com/scikit-image/scikit-image/archive/v{{ version }}.tar.gz
  # fn: scikit-image-{{ version }}.tar.gz
  # sha256: 8da6fb09aeefb757735c510650ac0072be3831fa76d9747285f3c6ea1e0c5a08
  patches:
    # https://github.com/scikit-image/scikit-image/pull/3558
    - 3558_dont_directly_call_test_fixtures.patch
    # https://github.com/scikit-image/scikit-image/pull/3561
    # https://github.com/scikit-image/scikit-image/pull/3556
    - 3561_numpy_1_16_fix.patch
    # https://github.com/scikit-image/scikit-image/pull/3637
    # https://github.com/scikit-image/scikit-image/pull/3572
    - 3637_filter_out_deprecation_pending_warning.patch


build:
  number: 1004
  script:
    - rm -rf skimage/viewer/tests  # we don't depend on Qt
    ########################################################
    # Remove these two lines at your own risk.
    #
    # pyproject.toml was getting detected by pip, and scikit-image was being built with modern numpy, not 1.11
    - rm pyproject.toml
    # I have no idea what this line actually fixes (other than speeding up the build a little bit)
    # I think windows was freaking out about path lengths, and maybe this fixed it???
    # https://github.com/conda-forge/scikit-image-feedstock/pull/39
    - "{{ PYTHON }} setup.py build_ext -j2"
    ########################################################
    - "{{ PYTHON }} -m pip install . --disable-pip-version-check --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv"
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.23.4,!=0.28.2,!=0.29.0
    - six >=1.7.3
    - numpy 1.11
    - scipy >=0.17
    - msinttypes  # [win and py<35]
  run:
    - python
    - six >=1.7.3
    - {{ pin_compatible('numpy') }}
    - scipy >=0.17
    - matplotlib >=2.0.0
    - networkx >=1.8
    - pillow >=4.3.0
    - toolz >=0.7.4
    - pywavelets >=0.4.0
    - dask-core >=0.9.0
    - cloudpickle >=0.2.1
    - imageio >=2.1.0
    # scikit-image depends on dask-array
    # which requires numpy, dask-core and toolz (cytoolz for speed)
    - cytoolz >=0.7.3

test:
  requires:
    - pytest
    - pytest-cov
    - numpy 1.11
  imports:
    - skimage
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    - pytest --pyargs skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
