{% set version = "0.13dev" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  git_url: https://github.com/scikit-image/scikit-image
  git_tag: master

build:
  number: 0

requirements:
  build:
    - setuptools 23.*
    - cython
    - python
    - six
    - numpy x.x
    - scipy
  run:
    - python
    - six
    - numpy x.x
    - scipy
    - matplotlib
    - networkx
    - pillow
    - dask
    - pywavelets

test:
  imports:
    - skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  summary: Image processing routines for SciPy

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
