{% set version = "0.13dev" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  git_url: https://github.com/scikit-image/scikit-image
  git_tag: master

build:
  number: 0

requirements:
  build:
    - setuptools 23.*
    - cython
    - python
    - six >=1.7.3
    - numpy x.x
    - scipy >=0.10.0
  run:
    - python
    - six >=1.7.3
    - numpy x.x
    - scipy >=0.10.0
    - matplotlib >=1.3.1
    - networkx >=1.8
    - pillow >=2.1.0
    - dask >=0.5.0
    - pywavelets >=0.4.0

test:
  imports:
    - skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  summary: Image processing routines for SciPy

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
