{% set version = "0.14.0" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  sha256: 325f75eb80fbc5371136e37f323445309ca9f65b6c6f718d0d0e2189e5de1224

build:
  number: 0
  script:
    - export LDFLAGS="-headerpad_max_install_names"  # [osx]
    - rm -f skimage/run-hessian.py
    - rm -rf skimage/viewer/tests  # we don't depend on Qt
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - python
    - pip
    - cython >=0.23
    - six >=1.7.3
    - numpy 1.11.*  # [not (win32 and py36)]
    - numpy 1.12.*  # [win32 and py36]
    - scipy >=0.17
    - numpydoc >=0.6
    - msinttypes  # [win and py<35]
  run:
    - python
    - six >=1.7.3
    - numpy >=1.11  # [not (win32 and py36)]
    - numpy >=1.12  # [win32 and py36]
    - scipy >=0.17
    - matplotlib >=2.0.0
    - networkx >=1.8
    - pillow >=4.3.0
    - dask-core >=0.15
    - toolz >=0.7.4
    - pywavelets >=0.4.0
    - dask[array] >=0.9.0
    - cloudpickle >=0.2.1
    - imageio >=2.1.0

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - skimage
  commands:
    - conda inspect linkages -p $PREFIX scikit-image  # [not win]
    - conda inspect objects -p $PREFIX scikit-image  # [osx]

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
    - ocefpaf
    - soupault
