{% set version = "0.16.2" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  sha256: dd7fbd32da74d4e9967dc15845f731f16e7966cee61f5dc0e12e2abb1305068c
  # url: https://github.com/scikit-image/scikit-image/archive/v{{ version }}.tar.gz
  # fn: scikit-image-{{ version }}.tar.gz
  # sha256: 3b8414ccb9b524d0d507909e9a4d3843af6ca9919152199d380f2b21639abf17

build:
  number: 1
  skip: True  # [py==27]
  script:
    - rm -rf skimage/viewer/tests  # we don't depend on Qt
    ########################################################
    # Remove these two lines at your own risk.
    #
    # pyproject.toml was getting detected by pip, and scikit-image was being built with modern numpy, not 1.11
    - rm -f pyproject.toml
    # I have no idea what this line actually fixes (other than speeding up the build a little bit)
    # I think windows was freaking out about path lengths, and maybe this fixed it???
    # https://github.com/conda-forge/scikit-image-feedstock/pull/39
    - "{{ PYTHON }} setup.py build_ext -j2"
    ########################################################
    - "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"
    # - "{{ PYTHON }} -m pip install . --disable-pip-version-check --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv"
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.25,!=0.28.2,!=0.29.0
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.19
    - matplotlib-base >=2.0.0
    - networkx >=2.0
    - pillow >=4.3.0,!=7.1.0,!=7.1.1
    - pywavelets >=0.4.0
    - imageio >=2.3.0
    # scikit-image depends on dask-array
    # which requires numpy, dask-core and toolz (cytoolz for speed)
    - dask-core >=0.15.0
    - toolz >=0.7.3
    - cytoolz >=0.7.3
    # cloudpickle is necessary to provide the 'processes' scheduler for dask
    - cloudpickle >=0.2.1

test:
  requires:
    - pytest
    - pytest-localserver
  imports:
    - skimage
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    # I'm really not sure why why this test is complaining about tk
    # I'm willing to leave it up to:
    #    - Nobody uses the tk backend
    #    - It is a temporary bug in Azure/conda-forge
    - pytest --pyargs skimage -k "io/tests/test_mpl_imshow.py::test_uint8"

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
