{% set version = "0.19.0" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  sha256: bcc79d06ca88ec081d1b0eacc0ae2ca3abbd993a5d89dc54fabe25f2480f0626
  # url: https://github.com/scikit-image/scikit-image/archive/v{{ version }}.tar.gz
  # fn: scikit-image-{{ version }}.tar.gz
  # sha256: 3b8414ccb9b524d0d507909e9a4d3843af6ca9919152199d380f2b21639abf17
  patches:
    - skip_pooch_during_tests.patch
    - fix_sum_keyword_rank.patch

build:
  number: 0
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.29.21,!=0.29.18
    - numpy
    - pythran
    - packaging >=20.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.4.1
    - networkx >=2.2
    - pillow >=6.1.0,!=7.1.0,!=7.1.1,!=8.3.0
    - imageio >=2.3.0
    - tifffile >=2019.7.26
    - pywavelets >=1.1.1
    - packaging >=20.0
    # scikit-image depends on dask-array
    # which requires numpy, dask-core and toolz (cytoolz for speed)
    - dask-core >=1.0.0,!=2.17.0
    - toolz >=0.7.3
    - cytoolz >=0.7.3  # [python_impl == 'cpython']
    # cloudpickle is necessary to provide the 'processes' scheduler for dask
    - cloudpickle >=0.2.1
  run_constrained:
    - matplotlib-base >=3.0.3
    - pooch >=1.3.0

# Issues reported upstream. Follow
# https://github.com/scikit-image/scikit-image/issues/4768

{% set tests_to_skip = "_not_a_real_test" %}
# https://github.com/scikit-image/scikit-image/issues/4774 - test_end_points fails on ppc64le with python 3.6, 3.7, 3.8 #4774
{% set tests_to_skip = tests_to_skip + " or test_end_points" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4773 - test_RGB fails on ppc64le with python 3.7 #4773
{% set tests_to_skip = tests_to_skip + " or test_RGB" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4772 - test_periodic_reference fails on ppc64le python 3.7 (conda feedstock) #4772
{% set tests_to_skip = tests_to_skip + " or test_periodic_reference" %}  # [ppc64le or aarch64]
# https://github.com/scikit-image/scikit-image/issues/4775 - test_hdx_rgb_roundtrip fail son osx with python 3.8 #4775
{% set tests_to_skip = tests_to_skip + " or test_hdx_rgb_roundtrip" %}  # [ppc64le or aarch64 or osx]
# https://github.com/scikit-image/scikit-image/issues/4776 test_hed_rgb_roundtrip fails on osx with python3.8 and ppc64le with python 3.6 #4776
{% set tests_to_skip = tests_to_skip + " or test_hed_rgb_roundtrip" %}  # [ppc64le or aarch64 or osx]
# https://github.com/scikit-image/scikit-image/issues/4778 - test_hed_rgb_float_roundtrip fails on ppc64le python 3.8 #4778
{% set tests_to_skip = tests_to_skip + " or test_hed_rgb_float_roundtrip" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4781 - test_ellipse_rotated fails on python3.8 #4781
{% set tests_to_skip = tests_to_skip + " or test_ellipse_rotated" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4785 - test_fixed_reference fails on ppc64le with python 3.7 #4785
{% set tests_to_skip = tests_to_skip + " or test_fixed_reference" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4782 - test_free_reference fails on ppc64le with python 3.6 #4782
{% set tests_to_skip = tests_to_skip + " or test_free_reference" %}  # [ppc64le]
# https://github.com/scikit-image/scikit-image/issues/4777 - test_uint16 fails on win #4777
{% set tests_to_skip = tests_to_skip + " or test_uint16" %}  # [win]
# TODO: Report this upstream
# It seems that the apply_parallel tests can have relatively small errors on windows
{% set tests_to_skip = tests_to_skip + " or test_apply_parallel_rgb" %}  # [win]

test:
  requires:
    - pytest
    - pytest-localserver
    # 2021/12/04: 0.19.0: hmaarrfk
    # We noticed that osx had strange failures with cythonized code
    # Testing with full datasets on OSX to ensure we don't have bugs
    - pooch  # [osx]
  imports:
    - skimage
  commands:
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    # A warning in numpy that makes tests fail has been fixed in 0.18
    # Remove this then.
    - SKIMAGE_TEST_STRICT_WARNINGS=0 pytest --pyargs skimage -k "not ({{ tests_to_skip }})"  # [unix]
    - set "SKIMAGE_TEST_STRICT_WARNINGS=0" & pytest --pyargs skimage -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: http://scikit-image.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Image processing in Python.
  description: |
    scikit-image is a collection of algorithms for image processing. 
    It is available free of charge and free of restriction. 
    We pride ourselves on high-quality, peer-reviewed code, 
    written by an active community of volunteers.

extra:
  recipe-maintainers:
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
    - emmanuelle
