travis:
  secure:
    BINSTAR_TOKEN: Pjd+YubuHEMRGVWRYZkcV0rGF5i1mOBLaADudjrFyICBmcIHAh302mVWVYCkTFlyD4OonJ5g52UBbbrR7lQ8rXQsbRoPE9WTvZUeBOgpdsF0QfHaHnncY/0X5Ne3dDnWB8FaX768AveX6YvfxMq5LvQrUeIOirUCGN26Sjmoz81PSI6ubtWqSnH9gKgs/e8i7o5x0QrmJgpAvGWV0DyfFBcjsqtqqdQ//FnEla6ETM6iXkZgbuGasCWIhwnzgugMgY8juX1u0W7eAfu8gF2tquFFElV/zL6K/KfvmHRubPZo+HplTBEsBBM2bNCo5YDqS2GM9gZGyM34eaijufJ9OSSfB2x3YGPXfhTCcU4hzWUTESCQLA01ySjJjptjhDvpVSVutuWqXSU6G9TlbJqT1unapBy1o/SC6uXipIZS3LKBx0GSNlBObYyF47nVKvr25Dh2u2NgcPGg3YqMbQpmSzdZ8DyCK0tyKdMoYd4gPTdFMBSGSvmu4oZ7NilbWs2faokY2PFvFrM7kfKKwnk2pwX9QzYwtbRg3yVDBoCZXkim5h6AQZYBDXbQjV3lJaRWzwGdKjuzUXdzwCp2fCGKBPY/SHfQqPitz9BMi2w5ISNlfVoiklDCqIjS2PKQiZOu0TcEzLVpJtuWWE2WVmMaS8XRaT0upyOY9/TthZaCE0k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
channels:
  targets:
    - [conda-forge, prerelease]
