compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
conda_forge_output_validation: true

# provider:
#   win: azure

# azure:
#   upload_packages: True
#   # I only want azure to build and upload windows
#   force: False
